# ----------------------
# STAGE 1: BUILD
# ----------------------
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src

# Копируем csproj отдельно — это ускоряет сборку за счёт кеша
COPY CatalogService.csproj ./
RUN dotnet restore

# Копируем остальные файлы
COPY . .
RUN dotnet publish -c Release -o /app/out

# ----------------------
# STAGE 2: RUNTIME
# ----------------------
FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS runtime
WORKDIR /app

# Копируем опубликованное приложение из предыдущего stage
COPY --from=build /app/out .

# Указываем порт
EXPOSE 5001

# Запускаем приложение
ENTRYPOINT ["dotnet", "CatalogService.dll"]